[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "/*"
  to = "/about"
[[redirects]]
  from = "https://sarahjlee.netlify.com/*"
  to = "https://sarahjlee.studio/:splat"
  status = 301
  force = true

